services:
  - type: web
    name: finio
    runtime: node
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build && cd .. && npm run seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
